package com.example.orquoll.swen90014_2018_or_quoll.db.initializeData;

import com.example.orquoll.swen90014_2018_or_quoll.R;
import com.example.orquoll.swen90014_2018_or_quoll.db.DAO.DAOFactory;
import com.example.orquoll.swen90014_2018_or_quoll.entity.Strength;

public class StrengthData {
    private DAOFactory newDAOFactory;

    public StrengthData (){
        this.newDAOFactory = new DAOFactory();
    }

    public void saveStrength(String tittle,String content,String description ,int drawableId){
        Strength strength = new Strength(tittle,content,description,drawableId);
        if(!strength.isSaved())
        strength.save();
    }

    public void saveAll(){
        saveStrength( "Courage\n","What makes you braver: bungee jumping or standing up for a kid who's being picked on? Sure, it takes nerve to step off a bridge with a rubber band round your ankle, but real courage is doing what you think is right, even when it's hard. It's doing the hard thing even when you're afraid. That's you. Your bravery makes you able to face your fears and do things you think are important.\n" +
                "\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/YyBk55G7Keo?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I give things a go, even when I feel nervous or afraid.\n",R.drawable.courage );
        saveStrength( "Creativity\n","Creative people love thinking of new ways to do things.  And it doesn't just mean in art: creative people have revolutionised science, sport, music Ã¢â‚¬â€\u009D everywhere, really. It doesn't matter if you love mixing up tracks or concrete, your imagination is always working. Did you ever have one of those moments where a new idea comes into your head, or a new move on the football field or the dance floor, or a rhyme or a picture or a formula or a recipe or some other exciting thing, and the amazing thing is that you imagined it out of nowhere? That's your creativity, an imaginative talent can be an enormous power in your life.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/HOMgDbcA84A?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I use imagination to respond to the world around me, coming up with unexpected solutions for problems.\n",R.drawable.creativity );
        saveStrength( "Curiosity\n","Why is the sky blue? What's over the next hill? What's over <em>that</em> one? Curious people want to know more. You find the whole world interesting, you go looking for new things to discover and you welcome new experiences. You're the kind of person who gets excited by words like <em>discover</em> and <em>explore</em> and especially <em>mystery</em>.\n" +
                "\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/GJ8u39PtFWU?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I ask a lot of questions, because the world is a fascinating place and Iâ€™m a natural explorer.\n",R.drawable.curiosity );
        saveStrength( "Discretion\n","Can you keep a secret? Can you stop yourself from spreading a bit of gossip if you know it'll hurt a stranger? Do you look before you leap? Yes you do. When everyone else jumps into a new craze, or fashion, you tend to sit back, have a good think about it, then make up your mind whether you're into it or not. You keep your cool. You don't make sudden decisions without knowing what you're deciding about. You know there's no rush, because getting it right in the long term is better than just jumping in and getting it wrong.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/9Fid9EHTkmk?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I weigh things up and choose my words carefully, taking time to make wise choices and careful plans.\n",R.drawable.discretion );
        saveStrength("Enthusiasm\n","Whatever it is, let's do it! You wake up in the morning excited about the day. You throw yourself into the things you do, treating life like an adventure you can't wait to continue. Pursuing things you're passionate about makes you happy. <iframe src=\"http://player.vimeo.com/video/42828824?byline=0&portrait=0&badge=0&color=00f137\" width=\"336\" height=\"189\" frameborder=\"0\" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>","I start the day with a sense of adventure, excited to see what comes next!\n",R.drawable.enthusiasm);
        saveStrength( "Fairness\n","Everyone gets the same sized piece of cake, right? 'Cause it'd be wrong for one person to get less or more than everyone else. That's how you feel: that everyone deserves to be treated as well as everyone else. You hate to see injustice in the world, whether it's among people you know or people on the other side of the world. You try to live by that principle, making a real effort to treat all people fairly.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/LA0BLrLW0PE?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I believe everyone should be treated equally and I make an effort to live by this principle.\n",R.drawable.fairness );
        saveStrength( "Forgiveness\n","If someone does you wrong, you forgive them. You don't go looking for revenge, and you tend to give people second chances. You're not the kind to be kept up at night gnawing away at old grievances, because you're good at letting things go and moving on.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/wt2VJn9_s3o?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I use compassion and hope to make sense of the past and to move into the future.\n",R.drawable.forgiveness );
        saveStrength( "Gratitude\n","You're really aware of the good things in your life: great people, fun times, even small things like sunny days and great music. They make you feel thankful, and that thankful feeling stays with you because you value those good things.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/8cTR6fk8frs?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I take time to think of the good things in life, and let people know I appreciate the things they do for me.\n",R.drawable.gratitude );
        saveStrength( "Honesty\n","Being honest isn't about strictly telling the absolute truth all the time. If you're honest, you're a person who is open with yourself about your thoughts, feelings and actions. You're genuine, because you don't pretend to be or think anything you're not. You try to give a true sense of yourself to the world, and if anyone gets the wrong idea about you, you try to correct it.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/M5vEYJDAv7k?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I donâ€™t just tell the truth, I live as truthfully as I can; others describe me as genuine, direct or down-to-earth.\n",R.drawable.honesty );
        saveStrength( "Hope\n","Hopeful people feel that the future is going to work out well. You could call it optimism: the feeling that no matter what, things are going to turn out for the best. You feel that if you work towards those good things you can have them.\n" +
                "<iframe src=\"https://player.vimeo.com/video/29938326\" width=\"500\"\" height=\"281\"\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href=\"https://vimeo.com/29938326\">THE BEGINNING OF INFINITY</a> from <a href=\"https://vimeo.com/jasonsilva\">Jason Silva</a> on <a href=\"https://vimeo.com\">Vimeo</a>.</p>\n","I know that tough times are temporary and things usually work out in the end.\n",R.drawable.hope );
        saveStrength( "Humour\n","You're funny in the best kind of way: the way that makes other people laugh and feel good. Your friends are always saying what a laugh you are, and they like you for it. You can see the funny in things, even things you take seriously, and you love to use that to make people, and yourself, happy.\n" +
                "<iframe width=\"336\" height=\"189\"\" src=\"https://www.youtube-nocookie.com/embed/zdtD19tXX30?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","I can see the funny side of most situations and I love to make other people laugh.\n",R.drawable.humour );
        saveStrength( "Kindness\n","Did you ever do a favour for someone, even though you didn't have to? What was it like to see how good it made them feel? Kindness is when you love to do nice things for other people, just because it makes them feel better. And making other people feel better makes you feel better, so you do it a lot.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/zzgllnPpMTs?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\"\n","I get a kick out of doing things for other people, even if itâ€™s just a kind word or smile.\n",R.drawable.kindness );
        saveStrength( "Leadership\n","\"Were you the kid who ran the hide-and-seek games in the playground? Do you always end up organising the groups you're in? Do you get picked as the captain in teams? That's your natural leadership showing. People look to you to be in charge because you're a good organiser and you know how to keep people working together well.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/MeJzHSxRq40?rel=0&modestbranding=1&iv_load_policy=3\" frameborder=\"0\"></iframe>\n","I like inspiring others to do great things and people often look to me for guidance.\n",R.drawable.leadership );
        saveStrength( "Love of learning\n","\"Did you know the German word for squirrel is EichhÃƒÂ¶rnchen, which means 'oak kitten'? Do you know what Graham's Number is? Or what's the heaviest weight a person has ever held over their head? What's a pulsar, or blanket stitch, or an augmented seventh, or Lady Gaga's real name? If you love learning, you've probably already Googled a few of those, or something like them.  Not for a job, or school, or to impress anyone, but just because learning new things makes you happy.\n" +
                "<iframe src=\"http://player.vimeo.com/video/27244727?byline=0&portrait=0&badge=0&color=00f137\" width=\"336\" height=\"189\" frameborder=\"0\" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>\"\n","I want to learn everything I can about people, places, ideas and things.\n",R.drawable.learning );
        saveStrength( "Love\n","There are all kinds of love: love for your boyfriend or girlfriend, your parents, kids, friends, pets. They all work differently, but the love you experience in your life gives you a deep sense of satisfaction. You know who you love, and they're the people who love you back. You feel loved and you trust the people who love you. You're comfortable showing your love and having other people show their love for you.\n" +
                "<iframe width=\"336\" height=\"189\" src=\"https://www.youtube-nocookie.com/embed/wDZUfGBUSeY?rel=0&modestbranding=1\" frameborder=\"0\"></iframe>\n","My close relationships are a source of comfort and joy, giving my life meaning.\n",R.drawable.love );
        saveStrength( "Modesty\n","\"When you win, you're proud and when lose, it sucks. But only a bit, because you can see that there are bigger things in the world. You feel important, but not the centre of the universe. You don't go looking for the spotlight, because you feel like everyone around you is just as important. That's modesty: it's when you feel good without having to have special attention.\n" +
                "<iframe src=\"http://player.vimeo.com/video/59464648?byline=0&portrait=0&badge=0&color=00f137\" width=\"336\" height=\"189\" frameborder=\"0\" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>\"\n","Iâ€™m comfortable with who I am and I know my own worth, so I donâ€™t need to seek out the spotlight.\n",R.drawable.modesty );
        saveStrength( "Open-mindedness\n","Open-mindedness, or good judgement, is thinking things through and examining them from all sides. It's a willingness to consider evidence against your own beliefs, plans, and goals, and to revise them if necessary. It's the opposite of stubbornness: instead of sticking to an opinion no matter what, you listen, consider the options and make well-judged decisions.\n" +
                "<iframe src=\"https://player.vimeo.com/video/69450259\" width=\"500\" height=\"281\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href=\"https://vimeo.com/69450259\">Pardon My Dust</a> from <a href=\"https://vimeo.com/snowglobestudios\">SnowGlobe Studios</a> on <a href=\"https://vimeo.com\">Vimeo</a>.</p>\n","I am open to new ideas and accepting of otherâ€™s beliefs, and I adapt easily to changing situations.",R.drawable.openmindedness );
        saveStrength( "Perseverance\n","3 steps forward, 1 step back. 3 steps forward, 2 steps back. 4 steps forward, 1 step back. But always going forward, right? Because that's you: when there are setbacks, like there are for everybody, you suck it up and keep pushing on, because you finish what you start. You're flexible too, because you know that sometimes the way forward isn't butting your head up against big problems but changing direction, trying something new. But whatever happens, you like to see things through.\n" +
                "<iframe src=\"http://player.vimeo.com/video/25397042?byline=0&portrait=0&badge=0&color=00f137\" width=\"336\" height=\"189\" frameborder=\"0\" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>\n","I am patient and determined, overcoming obstacles to complete what I have started.\n",R.drawable.perseverance );
        saveStrength( "Perspective\n","You have a wise way of looking at the world. You've got a knack for giving good advice, for thinking about difficult moral questions that people really appreciate. You've got a good strong sense of the meaning of things and how you fit into the world, because you tend to see the big picture rather than the tiny details.\n" +
                "<iframe src=\"http://player.vimeo.com/video/26378195?byline=0&portrait=0&badge=0&color=00f137\" width=\"336\" height=\"189\" frameborder=\"0\" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>\n","I have a knack for making sense of the world; friends come to me for advice, or just to hear my take on things.\n",R.drawable.perspective );
        saveStrength( "Self-control\n","You've got a job to do. Maybe homework, or a work thing, or some exercise. Something hard, not great fun, but something you've got to do that's good for you. But there's also that new game! There's Facebook! There's hanging out with your friends! There's a big tray of muffins in the fridge! You know what to do. You put all those ace things out of your mind for a while, resist temptation, and do the hard thing first. Then you get to reward yourself with the fun stuff, and it feels much better. That's self-control.\n" +
                "<iframe src=\"https://player.vimeo.com/video/62731783?color=cc0025&badge=0\" width=\"500\" height=\"281\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href=\"https://vimeo.com/62731783\">The Shoemaker</a> from <a href=\"https://vimeo.com/dustincohen\">Dustin Cohen</a> on <a href=\"https://vimeo.com\">Vimeo</a>.</p>\n","I can observe my thoughts and emotions and choose how to respond to them.\n",R.drawable.selfcontrol );
        saveStrength( "Social intelligence\n","If your friend is feeling down, do you notice, even if they don't say it out loud? Are you good at finding the right words to make people feel better? That's what social intelligence is. It's having a good sense of other people's emotions and knowing how to respond. Bonus points if you also feel you know your own feelings the same way.\n" +
                "<iframe src=\"https://player.vimeo.com/video/61320751\" width=\"500\" height=\"281\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href=\"https://vimeo.com/61320751\">Empathy Task</a> from <a href=\"https://vimeo.com/lukecollins\">Luke J. Collins</a> on <a href=\"https://vimeo.com\">Vimeo</a>.</p>\n","I have a good sense of how people feel and I know what to do to make them feel understood. \n",R.drawable.socialintelligence );
        saveStrength( "Teamwork\n","When you're in a group, you work well with everyone to help the team get where it's going. That could be a school group, work group, project group, gaming group, social group, sports group, music group, or any other time you're working together with people. When you're in that group, it's all about what the group needs, and you're willing to sacrifice your own needs for the group's needs.\n" +
                "<iframe src=\"https://player.vimeo.com/video/40980676\" width=\"500\" height=\"281\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>\n","Iâ€™m loyal to the group and work well with others, playing my part to get the job done.\n",R.drawable.teamwork );    }

}
